name: QA Testing Pipeline

# Define qué eventos van a disparar esta automatización
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    # Corre las pruebas sobre una máquina virtual con la última versión de Ubuntu Linux
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Baja el código de tu repositorio a la máquina virtual
    - name: Copiar el código del repositorio
      uses: actions/checkout@v4

    # Paso 2: Instala el entorno de ejecución de Python
    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Guarda en caché las librerías para que corra más rápido en las siguientes ejecuciones

    # Paso 3: Instala las dependencias que listamos en requirements.txt (pytest)
    - name: Instalar dependencias del proyecto
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Paso 4: El QA ejecuta la suite de pruebas completa
    - name: Ejecutar Pruebas Unitarias con Pytest
      run: |
        pytest tests/
